env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:jest/recommended
  - standard
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - jest
rules:
  react/prop-types: 
    - off
