env:
  browser: true
  es2021: true
extends:
  - standard
  - plugin:react/recommended
  - plugin:jest/recommended
  - plugin:tailwindcss/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - jest
  - tailwindcss
rules: {
  quotes: ["error", "double"],
  jsx-quotes: ["error", "prefer-double"]
}
